### ISSUE TITLE
[bug] main content rendering over itself

### ISSUE THREAD

**Issue by ltankey** [AusDTO/gov-au-ui-kit#132]
Content beneath our main class is rendering over itself, i.e.:

![image](https://cloud.githubusercontent.com/assets/5369670/16603353/b0126ea4-435e-11e6-9faa-08f413f85025.png)

I can reproduce this on the short.html example page in the ui-kit KSS:

http://gov-au-ui-kit.apps.staging.digital.gov.au/examples/short.html

![image](https://cloud.githubusercontent.com/assets/5369670/16603359/c762b424-435e-11e6-82b9-70adb562e9aa.png)

Although the content doesn't wrap over itself in this instance, the main margin left/right are excessively big which causes the ridiculous centering.

**Comment by TrebBrennan** [comment]
Looks like <main> needs a width?

**Comment by TrebBrennan** [comment]
Looks like `<main>` needs a width set?
Eg. Try 80%

**Comment by maxious** [comment]
Setting main 100% doesn't seem to have any ill effect and was the same solution in #111
