### ISSUE TITLE
Numeric input field that shows keypad on mobile browsers

### ISSUE THREAD

**Issue by jonathanconway** [AusDTO/gov-au-ui-kit#142]
We would like to pop up a numeric keypad when the user focuses on a numeric field, on mobile browsers:

![screen shot 2016-07-07 at 10 43 39 am](https://cloud.githubusercontent.com/assets/310330/16639097/cdf79e04-442f-11e6-95b7-f7b33aa49dde.png)

Currently, however, default browser behaviour is to show a mixed keypad with some numeric symbols and some characters:

![screen shot 2016-07-07 at 10 43 50 am](https://cloud.githubusercontent.com/assets/310330/16639109/dcac7b36-442f-11e6-93d7-6a7f82722c5a.png)

There are [hacks that can achieve this](http://danielfriesen.name/blog/2013/09/19/input-type-number-and-ios-numeric-keypad/). It would be great if we could have a common standard about how to do it.

**Comment by elisechant** [comment]
An  `<input type=number />` should do what you want. Probably this issue could be expanded to include a mix of the other array of type attribute permutations like type=email?

**Comment by jonathanconway** [comment]
@elise, sorry, I should have explained. The "mixed keypad" is shown when type=number. We currently have to use Daniel Friesen's hack (linked in my comment) to make it show a proper numeric keypad.

**Comment by elisechant** [comment]
A decision to go with the "hack option" says to me that the team values "use affordances" above "semantic affordances" (which I also agree with) - is that correct? Is there a way you can implement "the hack" method but also restore semantics perhaps using aria?

**Comment by TrebBrennan** [comment]
Our friends at GDS recommend this:

> Tip: If you want to trigger the num-pad on iPhones, add a pattern attribute to the input element like this: `pattern="[0-9]*"`
> https://www.gov.uk/service-manual/user-centred-design/resources/patterns/dates.html#memorable-dates

**Comment by jonathanconway** [comment]
Cool, @TrebBrennan! That looks much more minimal than the hack, and I don't think it would interfere with the semantics, to address @elisechant's point.

Might be good for I and others to check the Gov UK service manual in future as well.

**Comment by elisechant** [comment]
@jonathanconway seems like you were on the right path form the start - DO IT! Be sure to also document the quirk in the style guide and include those links. 

It's also a great idea to take a deep dive in to Gov UK service manual to find how other quirks that we might not yet know about are solved  - new JIRA task?

**Comment by jonathanconway** [comment]
> @jonathanconway seems like you were on the right path form the start - DO IT! Be sure to also document the quirk in the style guide and include those links.

Done. :)
