### ISSUE TITLE
Enhancement - Provide ability to remove border-top from vertical lists

### ISSUE THREAD

**Issue by simonschwartz** [AusDTO/gov-au-ui-kit#148]
The vertical lists should have a `border-top` when used for news items, however other vertical lists in the design should not have `border-top`. It would be great to be able to easily specify whether the component should or shouldn't have a `border-top`.

Example can be seen on the Agency Landing page 

**Current**

![before-listing](https://cloud.githubusercontent.com/assets/12635736/16716870/4f9462b6-474c-11e6-983f-fc59d67d13a8.png)

**Desired**

![after-listing](https://cloud.githubusercontent.com/assets/12635736/16716874/5d8b945c-474c-11e6-97b7-9f57b8cb31c1.png)

**Comment by klepas** [comment]
@simonschwartz would adding a reset that applies to these lists when nested in a say `section.news` or something work for you?

**Comment by simonschwartz** [comment]
@klepas That sounds reasonable. Currently we have 2 deviations of the listings in the prototype
- Homepage category list (border on left)
- Agency homepage responsibilities list (no border)

Maybe an initial approach default is no borders, `section.news` = border-top and `section.categories` = border left

Thoughts?

**Comment by klepas** [comment]
@simonschwartz or removing borders as the default? (derp that’s what you meant — sorry)

If you’re up in Syd, could you run this past Gaz to see if we can change our defaults instead of making special cases?

**Comment by simonschwartz** [comment]
Good point @klepas  Had a chat with @alzbetaT - going to hold off for now and let the designers do a stocktake of the varying listing styles and see if we can consolidate

**Comment by klepas** [comment]
Sounds good. (:
