### ISSUE TITLE
Bug - Side nav bounces when navigating between pages

### ISSUE THREAD

**Issue by hannah-ustwo** [AusDTO/gov-au-ui-kit#159]
## What I did

I was clicking between the guide's pages, browsing. (Chrome)
## What I expected to see

A stationary side nav
## What I saw

A side nav that bounced whenever I landed on a different page
![0d4fa3082bae7bcea2307315aa026e18](https://cloud.githubusercontent.com/assets/19661064/16792749/ba7447d6-490e-11e6-893e-e21356a059be.gif)

**Comment by klepas** [comment]
Fixed in https://github.com/AusDTO/gov-au-ui-kit/pull/160
