### ISSUE TITLE
Elaborate list view patterns have left alignment issues

### ISSUE THREAD

**Issue by klepas** [AusDTO/gov-au-ui-kit#170]
## What I did

Navigated to `examples/index.html` (http://gov-au-ui-kit-staging.apps.staging.digital.gov.au/examples/), scrolled down the page and noticed the left alignment of the custom list patterns (`_lists.scss`) commencing with `ul.list-horizontal` breaks out of the page grid, into the shifted gutter–column–gutter space between the main content area and the aside/local nav.
### What browser and device I was using

Chrome & FF.
## What I expected to see

Perfect alignment along the left main content margin.
## What I saw

![screen shot 2016-07-15 at 2 14 29 pm](https://cloud.githubusercontent.com/assets/52766/16863576/943c9156-4a97-11e6-8616-7491cc297fe5.png)
### Additional information (optional)

Might be worth noting that PR #169 includes a minor fix I made for the alignment of basic list item indentation that crept in probably over the last sprint or two (to re-align them with callouts, blockquotes, def lists, etc.).

See: https://github.com/AusDTO/gov-au-ui-kit/pull/169/commits/1442317c24782c714ef95fba7f1c24be861b1808

**Comment by TrebBrennan** [comment]
In `_typography.scss` there is a negative margin left set on all `<li>` elements.
`384: margin-left: -($small-spacing / 4);`
I imagine it was added to better optically align lists to body copy, but maybe we need to reassess how necessary this rule is if it means having to manually reset it on every list? #simplerClearerFaster

**Comment by klepas** [comment]
I just realised where this came from, and it’s me! :p

I added 0.2em padding to pad `li` from their bullet or ordered-list number for better readability and scanability, since they were a tad too close by default to the marker… and then used a negative margin to pull them back in line / align them with all the other type elements (def lists, callouts, etc).

I definitely want to keep list items aligned to all the other things… ahh, further things that should be fixed in a typography spike… I have been wanting to put a whole bunch of stuff in `_typography.scss` as only applicable when inside the main content space, which would fix stuff like this largely (in this instance it wouldn’t though…).

**Comment by TrebBrennan** [comment]
Yeah I had thought that we could specify it just for `.content-main li` but we have many types of other lists appearing in `.content-main` which we would have to specify a fix for, not to mention documenting this quirk for future users.

I think it would be worth reassessing the effort versus value of this one.

**Comment by TrebBrennan** [comment]
@Fixed in #257
