### ISSUE TITLE
Bug - Buttons and input field sizing too small for touch

### ISSUE THREAD

**Issue by phil-banks** [AusDTO/gov-au-ui-kit#179]
## What I expected to see

From memory i think that we had these originally at 48pxH (3emH, ?? rem) to account for touch screen/mobile devises. 
## What I saw

currently these are in at 2.4 emH, disregard if this is a conscious decision

**Comment by TrebBrennan** [comment]
Thanks @phil-banks, it was not a conscious decision.
We'll need to review. Good pickup.

**Comment by phil-banks** [comment]
cool @TrebBrennan,  QQ is this the right forum for these styling type issues?

**Comment by TrebBrennan** [comment]
We accept all questions! If you think it could be an issue or something that was overlooked just ask :)
