### ISSUE TITLE
No visual differentiation between h1 and .abstract on section page in mobile browser

### ISSUE THREAD

**Issue by streetdaddy** [AusDTO/gov-au-ui-kit#227]
/via Michelle Mortimer
# Expected

Page heading text size should be larger than Abstract
# Actual

Text size is the same for both elements
# Steps to reproduce

Visit https://gov-au-beta.apps.platform.digital.gov.au/television-tv-reception/troubleshooting-tv-reception in Chrome Inspector with Iphone 6 in portrait as the device

![Screenshot from Chrome Inspector](https://www.evernote.com/l/ABbClbqfEBNLvbPhJlNIHCO1h-qRZ9ny39oB/image.png)

**Comment by klepas** [comment]
Confirming this a responsive font-size bug.

Thanks — will fix Monday.

**Comment by hannah-ustwo** [comment]
Got this in progress on Guide's backlog with @klepas on it. Added "roadmap" label.

**Comment by klepas** [comment]
Got a proposed fix as a PR up. (:

**Comment by klepas** [comment]
Fixed in 1.7.0.
