### ISSUE TITLE
Bug - Documentation differs between examples and latest release SCSS

### ISSUE THREAD

**Issue by ltankey** [AusDTO/gov-au-ui-kit#228]
## What I did

Provided markup for a local-nav as per https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html
### What browser and device I was using

MBP 13'', Chrome
## What I expected to see

I expected, following the markup example, to get a nav with predictable indentation as per:
![image](https://cloud.githubusercontent.com/assets/5369670/17265935/81b5b2e2-5636-11e6-83f6-b019422dee1c.png)
## What I saw

The result looked like:
![image](https://cloud.githubusercontent.com/assets/5369670/17266243/2460c78c-5639-11e6-93b0-afde671f2c8c.png)
### Additional information (optional)

The indentation appears erroneous and is applied by `.local-nav ul ul a`, however the example on the example link posted above clearly outlines a need for this markup.

This example page http://gov-au-ui-kit-staging.apps.staging.digital.gov.au/examples/header-home.html which demonstrates the new header style has different markup itself, which is a point of confusion around what is a canonical example to use to implement the navbar.

The markup for the incorrect indentation image is:

```
        <nav aria-label='main navigation' class='local-nav'>
          <a aria-controls='primary-nav-panel' aria-expanded class='js-accordion-trigger nav-heading' href='javascript:void(0)' id='primary-nav-heading'>
            <span>Show menu</span>
            <i class='chevron bottom'></i>
          </a>
          <ul aria-labelledby='primary-nav-heading' id='primary-nav-panel'>
            <li>
              <a>Heading</a>
              <ul>
                <li>
                  <a href='/minister-for-communications/responsibilities'>
                    Responsibilities
                  </a>
                </li>
                <li>
                  <a href='/minister-for-communications/about-the-minister'>
                    About the Minister
                  </a>
                </li>
                <li>
                  <a class='is-active' href='/minister-for-communications/news'>
                    News
                  </a>
                </li>
                <li>
                  <a href='/minister-for-communications/contact'>
                    Contact
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
```

**Comment by ltankey** [comment]
A followup: the `is-current` class which is documented no longer works, and appears to have been replaced by `current`? However this change doesn't appear to be documented anywhere.

**Comment by TrebBrennan** [comment]
Thanks for the report Luke.

`.is-active` and `.is-current` should work as documented inside `.local-nav` 
To help us confirm where the issue is, could you temporarily remove all the CSS you are using and load [this file](https://gov-au-ui-kit.apps.staging.digital.gov.au/latest/ui-kit.min.css) instead and let us know if the `.local-nav` is behaving as expected?

Also sorry for adding to the confusion; all examples in the `/examples` directory are for test only and shouldn't be considered documentation. If something referenced in documentation conflicts with these example pages please consider the documentation to be the source of truth.

Let me know how you go!
( I'll aim to make sure our example pages are better updated ;) )

**Comment by ltankey** [comment]
Hey @TrebBrennan if you check out the 1.5 scss file on the following line you'll see it's no longer in line with the `is-current` examples:https://github.com/AusDTO/gov-au-beta/blob/develop/vendor/assets/stylesheets/_ui-kit.scss#L7294 

Appreciate your help, happy to try out your suggestion and report back when I'm in front of a screen. I think this is just a case of implementation and documentation being out of step :)

**Comment by ltankey** [comment]
I'm going to self close this, as if we treat documentation suitable for latest only the markup in the examples matches the implementation. I think we just got into some confusion with the pace of changes and releases.
