### ISSUE TITLE
Feature request - link styling for logo as link on mobile

### ISSUE THREAD

**Issue by maxious** [AusDTO/gov-au-ui-kit#246]
As per https://github.com/AusDTO/gov-au-beta/issues/356 want to make the image a link.
Default link styling is to make it all white which makes the logo hard to read. Consider what is a good link styling color for this use case.

**Comment by TrebBrennan** [comment]
hot-fix for now:

```
a.govau--logo:hover .brandbar,
a.govau--logo:focus .brandbar,
a.govau--logo:active .brandbar,
a.govau--logo:hover .b1,
a.govau--logo:focus .b1,
a.govau--logo:active .b1,
a.govau--logo:hover .b2,
a.govau--logo:focus .b2,
a.govau--logo:active .b2{
    background:white;
}
a.govau--logo:hover, a.govau--logo:focus, a.govau--logo:active {
    border-bottom: none;
}
```

**Comment by maxious** [comment]
Tweaked so the logo main isn't all white https://github.com/AusDTO/gov-au-beta/blob/develop/app/assets/stylesheets/_logo-link.scss

```
a.govau--logo, a.govau--logo:hover, a.govau--logo:focus, a.govau--logo:active {
  border-bottom: none;
}

a.govau--logo:hover, a.govau--logo:focus,a.govau--logo:active {
  background-color: transparent;
}

a.govau--logo:hover .brandbar,
a.govau--logo:focus .brandbar,
a.govau--logo:active .brandbar,
a.govau--logo:hover .b1,
a.govau--logo:focus .b1,
a.govau--logo:active .b1,
a.govau--logo:hover .b2,
a.govau--logo:focus .b2,
a.govau--logo:active .b2{
  background:white;
}
```

**Comment by klepas** [comment]
@maxious Close this? We need to pull this tech debt out, but the issue itself should be fixed for demo, right?

**Comment by maxious** [comment]
Can you include it in your prerelease header so I can remove the custom SCSS in beta?

**Comment by hannah-ustwo** [comment]
Any updates on this? Should we roadmap or close this? @klepas

**Comment by maxious** [comment]
Roadmap a review and refactor of prerelease header including responsiveness? 
We're definitely still using the logo as a homepage link.

**Comment by klepas** [comment]
Tracked in `DESIGN-292`, which covers the whole prerelease header; closing this tix.
