### ISSUE TITLE
Beta badge color doesn't match dto.gov.au

### ISSUE THREAD

**Issue by maxious** [AusDTO/gov-au-ui-kit#247]
Badge in #242 and badges in typography section don't match the colors on https://www.dto.gov.au/standard/service-design-and-delivery-process/

**Comment by klepas** [comment]
I see this as general tech debt — the badge shouldn’t be an image to begin with.

**Comment by maxious** [comment]
Note that also the badges in the typography section which aren't images also do not match dto.gov.au

**Comment by klepas** [comment]
Marking this as general tech debt (the gov-au prerelease header); I’m going to close this since it will be covered when we address that header.
