### ISSUE TITLE
Feature request: Single checkbox mandatory error state

### ISSUE THREAD

**Issue by channyvw** [AusDTO/gov-au-ui-kit#250]
## What I did

Followed the example for a checkbox field from the style guide.
# What browser and device I was using

Not applicable
## What I expected to see

I wanted to style the checkbox for an error state as our single checkbox is meant to be mandatory.
## What I saw

Not applicable
### Additional information (optional)

![screen shot 2016-08-04 at 11 23 44 am](https://cloud.githubusercontent.com/assets/19541725/17387400/d19ec970-5a36-11e6-93f2-43b0b46b9488.png)

**Comment by klepas** [comment]
This relates to form validation, and form patterns (mandatory fields, etc.).

Tracked (at least in part) under `DESIGN-277`.

Not sure when we will get to this given our current backlog and priorities — @channyvw can you let us know if you proceeded on this; we might be able to use/build on your solution. (:

**Comment by channyvw** [comment]
@klepas I didn't get anywhere on it as it was a rush to get our Beta out the door unfortunately. No one has mentioned it as a bug in our project and we only have one instance where it is required. My current solution which is an extension of the UK error handling was to list it as an invalid field in a callout box above the form region. Since you've got it tracked in DESIGN-277 I think this issue can be closed???

**Comment by klepas** [comment]
@channyvw thanks! (: I’m gonna close this.
