### ISSUE TITLE
Bug - [Vertical lists box-sizing issue in Internet Explorer 10/11]

### ISSUE THREAD

**Issue by simonschwartz** [AusDTO/gov-au-ui-kit#252]
## What I did

Viewed the gov.au homepage on  
### What browser and device I was using

Windows 8.1 Internet Explorer 11
## What I expected to see

The `.list-vertical--thirds` list to display list items in 3 columns when viewed on screen sizes equal to or above tablet size.
## What I saw

List items rows incorrectly breaking.

![flexbox-ie11](https://cloud.githubusercontent.com/assets/12635736/17390164/cf0d615a-5a4d-11e6-830b-c2a2d4de8173.png)
### Additional information (optional)

This bug is specific to IE10/11 and caused due to this specific browser ignoring box-sizing.

I fixed this bug in the platform by specifying a max-width on the list items.

**Comment by klepas** [comment]
Fixed by #305.
