### ISSUE TITLE
Bug - 'gulp-svg2png' fails during build on Windows

### ISSUE THREAD

**Issue by ashnewport** [AusDTO/gov-au-ui-kit#255]
## What I did

Cloned the repo then ran `npm install` and `gulp build` having made no modifications to the code at this point.
### What browser and device I was using

Windows 10, Git Bash
## What I expected to see

`Style guide build completed successfully!` logged in the terminal window.
## What I saw

```
[09:19:22] Starting 'svg2png'...

C:\Users\Ash\Documents\Work\gov-au-ui-kit\node_modules\gulp-svg2png\index.js:49
        throw new gutil.PluginError(PLUGIN_NAME, message);
        ^
Error: Error while converting image.Error: TypeError: 'undefined' is not a function (evaluating 'el.getBBox()')

  phantomjs://webpage.evaluate():5
  phantomjs://webpage.evaluate():35
  phantomjs://webpage.evaluate():35
Unable to calculate dimensions.
TypeError: 'null' is not an object (evaluating 'dimensions.width')
```
### Additional information (optional)

Adding XML declaration to the start of `.svg` files where it was missing solves the issue.

`<?xml version="1.0" encoding="UTF-8"?>`

If the above was omitted for optimisation but again needs to be included for Windows to play nice, perhaps the addition of [SVG Optimizer](https://www.npmjs.com/package/svgo) might come in handy. Node package for Gulp is [gulp-svgo](https://www.npmjs.com/package/gulp-svgo).

**Comment by TrebBrennan** [comment]
@maxious FYI

**Comment by klepas** [comment]
@ashnewport what an awesome bug report — thank you. :D

**Comment by elisechant** [comment]
it's going to be hard to support Windows cli. Recommend vagrant environment option or ignore Windows.  Windows is notoriously horrible on CL.
