### ISSUE TITLE
Feature request - form validation error messages or error summary blocks

### ISSUE THREAD

**Issue by elisechant** [AusDTO/gov-au-ui-kit#265]
I can see you have invalid form inputs, but I'd like to also have an error message directly beneath that invalid input and/or a summary error block at the top of form (and probably more accessible).

**Comment by TrebBrennan** [comment]
Hey @elisechant
Something like the [convo that is happening in 218](https://github.com/AusDTO/gov-au-ui-kit/issues/218#issuecomment-236571803)?

**Comment by elisechant** [comment]
@TrebBrennan ah cool. sweet.
