### ISSUE TITLE
Bug - Location of 'Accessibility & browser testing' accordion

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-ui-kit#282]
## What I did

Visited most KSS pages and looked for component examples.
## What I expected to see

The component example before the 'Accessibility & browser testing' accordion (not the other way around).
### Additional information (optional)

I'm aware there's a limitation with the KSS thanks @klepas - just logging it here for when we have a chance to change this.

**Comment by klepas** [comment]
Fixed.
