### ISSUE TITLE
Bug/question - logos should be images instead of free text

### ISSUE THREAD

**Issue by elisechant** [AusDTO/gov-au-ui-kit#308]
Not sure if this is a bug or a feature. 

Logos are free text instead of images. This means they can't be "downloaded" or referenced by external sites like Google! Image logos are sort of also needed by manifest and image type meta tags for SEO etc. 

I would have thought they should be images (svgs) but not sure whether we decided to do them this way for a reason.  

<img width="913" alt="screen shot 2016-08-28 at 3 07 15 pm" src="https://cloud.githubusercontent.com/assets/2195815/18031733/3f1963d6-6d31-11e6-853d-675d8153ff1c.png">
<img width="1006" alt="screen shot 2016-08-28 at 3 06 53 pm" src="https://cloud.githubusercontent.com/assets/2195815/18031734/3f1a48f0-6d31-11e6-8657-f0cdd87506ec.png">

**Comment by TrebBrennan** [comment]
Thanks @elisechant for the feedback.
This is expected on our end at the moment, as no logos have been approved for production yet.

**Comment by klepas** [comment]
Do boring things need logos? ^_^

#controversial

(There’s no Jira tix for this yet btw, and haven’t made one yet… thoughts?)

**Comment by klepas** [comment]
Closing this — we’ve got a logo svg/png for the guides now, and we won’t be shipping them in UI-Kit.
