### ISSUE TITLE
Bug - multiline label text for checkboxes

### ISSUE THREAD

**Issue by ltankey** [AusDTO/gov-au-ui-kit#310]
## What I did

Used checkboxes with multiline labels for a checkbox:

```
      %label{for: :sms}
        %p Send a text message
        %p something else
```
### What browser and device I was using

OSX MBP 13'' Retina
## What I expected to see

The checkbox should  align like this design diagram:

![screen shot 2016-08-29 at 8 38 06 am](https://cloud.githubusercontent.com/assets/5369670/18037302/f7cc5ac2-6dc3-11e6-9c2e-d9088f7d1a7d.png)
## What I saw

Alignment of the checkbox is off:
![image](https://cloud.githubusercontent.com/assets/5369670/18037310/170876e6-6dc4-11e6-9fff-0dd5be7f1ae9.png)

**Comment by TrebBrennan** [comment]
Resolved in person.
`<p>` is not valid inside `label` only [Phrasing Content (text)](https://www.w3.org/TR/html5/dom.html#phrasing-content-1) is valid.

Solution was to move the `p` outside of `label` and custom style `label+p` with a matching indent.
