### ISSUE TITLE
Script error in Windows 8.1 / IE 11 latest loading zoo page

### ISSUE THREAD

**Issue by streetdaddy** [AusDTO/gov-au-ui-kit#321]
## What I did

Browser testing from manual test plan
### What browser and device I was using

Windows 8.1 / IE 11 latest via Browserstack

![bs_win8 1_ie_11 0](https://cloud.githubusercontent.com/assets/795921/18079409/da7b165a-6ed3-11e6-8475-10e4caabe428.jpg)

**Comment by TrebBrennan** [comment]
iOS9

<img width="1399" alt="screen shot 2016-09-06 at 1 43 35 pm" src="https://cloud.githubusercontent.com/assets/15899197/18262686/42587204-7447-11e6-80e9-ce2415af88d2.png">

**Comment by TrebBrennan** [comment]
Closing for duplicate bug https://github.com/AusDTO/gov-au-ui-kit/issues/307
