### ISSUE TITLE
'Skip to section navigation' skips to main content

### ISSUE THREAD

**Issue by streetdaddy** [AusDTO/gov-au-ui-kit#322]
## What I did

During browser testing, I followed the 'Skip to section navigation link'
### What browser and device I was using

Windows 8.1 / IE 11 via Browserstack
## What I expected to see

Scroll down with Section navigation visible and next in the tab order
## What I saw

Scrolled down past the Section navigation and the tab order was still up in the header.  Screenshot shows where the page scrolled to.

![bs_win8 1_ie_11 0 1](https://cloud.githubusercontent.com/assets/795921/18079503/774becc0-6ed4-11e6-8716-df2ef48670a3.jpg)

**Comment by joolswood** [comment]
Also occurs on Chrome for Windows 10

**Comment by klepas** [comment]
I can’t replicate the bug on any of the combinations either of your listed @joolswood / @streetdaddy … :S

**Comment by TrebBrennan** [comment]
@klepas I just tried it in IE11 on browser-stack and it's definitely an issue, it sounds like the exact same bug as `DESIGN-394` which is related to the findings on #300.

In basic. IE scrolls down, but focus is not moved. So the next time you push tab you a returned your previous position.

**Comment by klepas** [comment]
Thanks @TrebBrennan. I’ve linked to this also under `DESIGN-394`.

**Comment by klepas** [comment]
Closing since this is a duplicate of #300.
