### ISSUE TITLE
No visible focus on Section menu when keyboard tabbing

### ISSUE THREAD

**Issue by streetdaddy** [AusDTO/gov-au-ui-kit#323]
## What I did

Tabbing through page with the keyboard, with a mobile resolution so the Section navigation is collapsed with the 'Menu' link showing.
### What browser and device I was using

Reproduced in both Windows 8.1 / IE11 latest via Browserstack, and Chrome latest on OSX.
## What I expected to see

Some visual indication that I have the 'Menu' link focussed so I know to hit Enter or Space to toggle it.
## What I saw

No visual difference from the normal appearance

<img width="397" alt="topic_landing_page" src="https://cloud.githubusercontent.com/assets/795921/18079695/719fcebc-6ed5-11e6-96d8-322ecf07fbc5.png">

**Comment by klepas** [comment]
Fixed in `1.8.0`.
