### ISSUE TITLE
Bug - partial underlining for external link that wraps

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-ui-kit#340]
## What I did

Resized screen to 375x667.
### What browser and device I was using

Safari on OS X (latest versions).
## What I expected to see

Underlining for whole link.
## What I saw

![screen shot 2016-09-02 at 1 46 57 pm](https://cloud.githubusercontent.com/assets/13774080/18192527/a717c398-7118-11e6-9827-0cc335e6aedc.png)

**Comment by klepas** [comment]
This should be fixed in `1.8.0` today, thanks to @alecky. (:

**Comment by klepas** [comment]
Fixed by release `1.8.0`: https://github.com/AusDTO/gov-au-ui-kit/releases/tag/1.8.0
