### ISSUE TITLE
Bug - feedback button disappears on mobile

### ISSUE THREAD

**Issue by tessereth** [AusDTO/gov-au-ui-kit#348]
Currently we include a feedback button in the header, using the following markup.

```
<div class="feedback">
  <a class="button--feedback" role="button" href="/feedback/new">Give Feedback</a>
</div>
```

But when going down to mobile sizes, the button disappears. Originally the button would move into the global nav but if the global nav is now deprecated, we need a new solution.

**Comment by klepas** [comment]
Tracked under `DESIGN-439`.

**Comment by joolswood** [comment]
Linked to #372

**Comment by klepas** [comment]
Noting I just ran into this again.

Treb noted that we resolved this by adding a feedback anchor to the footer, which is hidden except for in mobile view.

**Comment by klepas** [comment]
Closing this since #372 effectively fixes this problem.
