### ISSUE TITLE
H1 should be in the content body

### ISSUE THREAD

**Issue by ltankey** [AusDTO/gov-au-ui-kit#38]
Currently the H1 is in the nav/title bar, which should probably be reserved exclusively for the brand/logo (if it's to take on the role as a more traditional nav).

It would be great to shift the H1 into the content body, so that the markup could properly reflect each page's titles properly.

**Comment by maxious** [comment]
https://github.com/AusDTO/gov-au-ui-kit/blob/master/examples/index.html#L44

**Comment by klepas** [comment]
I’ll fix this in the header/footer edits I’m working on.
