### ISSUE TITLE
Feature request - code styling

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-ui-kit#380]
## What I did

Browsed guide pages.
### What browser and device I was using

Chome, OSX.
## What I expected to see

Clear styling (eg pink/red text on grey background) for code text and snippets.
## What I saw

Use of a different font  --- but this is not as clear as pink on grey.
### Additional information (optional)

See style used here: https://pages.18f.gov/content-guide/technical-and-interface-writing/#code

**Comment by klepas** [comment]
We get syntax styling out of the box essentially with Jekyll. Happy to also improve code styling in general/when it doesn’t receive a particular syntax highlighting style.

**Comment by klepas** [comment]
Tracked under `DESIGN-485`.

**Comment by klepas** [comment]
Currently in `develop` in the dto-design-guide.

**Comment by klepas** [comment]
I don’t know of any user need to represent code at the moment within the UI-Kit — we have many needs for it elsewhere, but when we do need to syntax highlight code in documentation/elsewhere we can do it using the future generic guides theme, or a dev will implement something to suit their needs, so I’m going to close this.

[tl;dr: don’t think we have a direct user need to ship syntax highlighting for various languages in our SASS/CSS]
