### ISSUE TITLE
feature request - optionally include grid classes

### ISSUE THREAD

**Issue by elisechant** [AusDTO/gov-au-ui-kit#386]
Given documentation: 

> "Grid classes? There are no non-semantic grid classes with which to set block elements. This is intentional. If you need to add to or customise the grid system see below."

But it would be really great to have a grid just work out of the box or perhaps point to an example code sample.

**Comment by klepas** [comment]
Closing this; while #412 is a duplicate, there’s a bunch of resources and chats that have started in the other issue thread.

Thanks for raising.
