### ISSUE TITLE
Is there a design guideline for "optional" form field?

### ISSUE THREAD

**Issue by elisechant** [AusDTO/gov-au-ui-kit#389]
## What I did

Creating optional form elements. Following the documentation that says: 

> If you have to ask for optional information mark the field labels with ‘(optional)’.

Should I render "optional" like:

`<label>Name (optional)</label>`

or is there a recommended design pattern to do this? 

What comes to mind is: 

`<label>Name <sup>(optional)</sup></label>`

**Comment by klepas** [comment]
Sorry to get back to this so late @elisechant 

Semantically I would not use superscript, but a span instead, and control the styling via `vertical-align`, and adjusting it’s font size the same way.

If you do lower the font size don’t go under 14px.

Few egs from a quick play:

![screen shot 2017-01-10 at 3 39 03 pm](https://cloud.githubusercontent.com/assets/52766/21794094/57760572-d74b-11e6-873e-0ed77b70e4cb.png)

![screen shot 2017-01-10 at 3 38 04 pm](https://cloud.githubusercontent.com/assets/52766/21794097/5e5a6856-d74b-11e6-891d-873bb508e67b.png)

If there’s value in this I’d be glad to add these to the forms module for 2.x. Thoughts?

**Comment by klepas** [comment]
cc @lreichelt

**Comment by lreichelt** [comment]
conscious that it is incredibly annoying to do this when you've just closed the issue... I'm wondering, what is the user need for an optional field? I'd prefer our guidance to government was to not have optional fields. Why are we asking for information if we don't absolutely need it?

**Comment by klepas** [comment]
@lreichelt—

> I'd prefer our guidance to government was to not have optional fields. Why are we asking for information if we don't absolutely need it?

Generally agree, and is similar to [our current guidance on the subject](http://guides.service.gov.au/design-guide/components/forms-buttons/index.html#optional-mandatory-fields).

We’ve been asked how to denote optional fields in the past. Our advice is to not ask that question then at all, and if you absolutely must:

> If you have to ask for optional information mark the field labels with ‘(optional)’.
