### ISSUE TITLE
Workshop: Workflow for request intake

### ISSUE THREAD

**Issue by gazhands** [AusDTO/gov-au-ui-kit#398]
Goal: Determine a new workflow that streamlines and clarifies how the UI kit or Guides take requests - for us internally and for clarity externally

**Comment by joolswood** [comment]
@hannah-ustwo @gazhands @klepas before we close off this properly I'm keen to review your [workshop findings](https://docs.google.com/a/digital.gov.au/document/d/19UMOcYh_4mf0bXkVo6QoChM1goDHsiSg_VWk3kMIZh8/edit?usp=sharing) in light of the Content Guide, given that it has some existing workflow.
