### ISSUE TITLE
Review existing related research from other DTO teams

### ISSUE THREAD

**Issue by hannah-ustwo** [AusDTO/gov-au-ui-kit#399]
Find and review any existing research around users needs related to Guides.

Teams/people to talk to:
- DSS
- Rod M
- Jacqui
- Jordan

Ask about:
- Workflow
- User needs
- Painpoints in the creation of digital transformations and products at DTO

(Looking to gain insights on how people work on a daily basis. What workflows they go through, who are they interacting with, what are their needs, pains. I also want to know how the ui-kit/guide has affected their workflows so far, what their expectations were, and how they were met (or not) as a form of auditing our current product.)

**Comment by joolswood** [comment]
As discussed in planning, I can take on the existing DSS material to start with.

I've set up a [previous guides UR GDoc](https://docs.google.com/document/d/1RaYFtZ3gAn91cUaxQ8nSORC3vSl3VkaU0UqakZfuV4I/edit).

**Comment by joolswood** [comment]
I've done a very quick timeboxed survey of the [old research referenced in this doc](https://docs.google.com/document/d/1RaYFtZ3gAn91cUaxQ8nSORC3vSl3VkaU0UqakZfuV4I/edit).

Much of it is too old/in a different context to be useful, but of what was I've added highlights to the Trello board.

I'll just note a few of these things I just added, as we didn't have them on the board when we did the workshop with @hannah-ustwo 
- Build a community / forums, discussion groups, lists of community practice
- Must include principles
- Need to show what is mandatory and what is flexible
- Needs good IA and search / break content down into small practical chunks
- Why the style needs to be used - ie legal and accessibility
- Explain decisions based on research and show successful case studies
- Must have practical info - no nice to have
- Version control / revision history

I'm going to consider this task done, as the Thinkplace research is technically new so we should treat it as a separate task when it is available

**Comment by joolswood** [comment]
Actually, just before we close off, @gazhands can you / have you spoken to Jordan so we can finish this off? Happy to do this myself, also.

**Comment by hannah-ustwo** [comment]
@joolswood @gazhands I'm happy to move this to done if you guys are!
