### ISSUE TITLE
Interviews with the Guides' users about the existing workflow/clarity/contribution.

### ISSUE THREAD

**Issue by gazhands** [AusDTO/gov-au-ui-kit#400]
- Definition of Done
- Create discussion guide that aims to get insights on the existing pain points in contributing to the guide
- Conduct interviews
- Document insights

People we may want to interview:

DEVS
Elise, Nathan, Jonathan Conway, Catherine Jones, Alistair, Rowan, Simon

DESIGNERS
Alzbeta, Phil, Jeremy, Leisa

CONTENT
Michael Hugill, Michelle, ~~Trisha~~ Zoe

**Comment by hannah-ustwo** [comment]
Also consider:

> Does the BROWSER-SUPPORT.md and individual component content meet users needs around level of browser support?
> 
> As a UI-KIT team member I need to know if we are meeting our users' needs around the browser support level of all parts of the framework - so we know how to improve our documentation.

**Comment by joolswood** [comment]
@gazhands and @hannah-ustwo I'm happy/keen to talk to the content people, but I think this would require someone setting up lookback on their machine in Sydney? (can't record a hangout, easily)

Trisha has left, but I could interview Zoe here in Canberra instead. She's new to the DTO/content guide but would probably have experience with other content guides from previous work.

**Comment by gazhands** [comment]
Good idea with Zoe, try for her if you get a chance.

**Comment by joolswood** [comment]
Ok, Zoe is booked in for midday tomorrow.

**Comment by gazhands** [comment]
2 interview done today. Al -Designer, Nathan - FE Dev

**Comment by hannah-ustwo** [comment]
Awesome stuff!!!

Can we document the notes and Lookback links in this gdoc here? I'll do the same for the ones we do today or tomorrow.
https://docs.google.com/document/d/1jAIHG9joLM94st_lLCkcKVTb91tBfznsUrwngH3r3OY/edit

**Comment by hannah-ustwo** [comment]
Meeting with Jonathan Conway today at 4PM, looking to make a few more bookings this afternoon and tomorrow  after the IA review from 10-11AM  :)

**Comment by hannah-ustwo** [comment]
Meeting with Michael Hugill today at 3:15, and Treb booked in for tomorrow 11AM. Huzzah.

**Comment by klepas** [comment]
I looked over the notes for Treb and made only a few minor edits, and added a few `(?)` to notes I wasn’t sure about/confused me a bit.

I think you captured everything otherwise Hannah — I don’t really have anything to add.
