### ISSUE TITLE
Purpose statement for UI-Kit and Design Guide

### ISSUE THREAD

**Issue by hannah-ustwo** [AusDTO/gov-au-ui-kit#403]
As a user I need a very simple explanation of what this is / what it is for so I know if this is for me.

**Comment by joolswood** [comment]
Ok, starting from our team's mission `Collaborating to build tools and guidance to empower government to transform services for our users` and paring down to minimal words (we can add more to this, just a starting point):
- UI-Kit: a CSS and JavaScript framework for building Australian Government services
- Design Guide: A guide to using the [UI-Kit framework]() to build Australian Government services

**Comment by klepas** [comment]
@joolswood Heya, anything we do with this currently, or is this something related to #426?

**Comment by joolswood** [comment]
@klepas yes definitely related. At minimum it'll define the home page words. It also may flow into the principles.

**Comment by hannah-ustwo** [comment]
@gazhands to help this along
