### ISSUE TITLE
bug - breadcrumbs don't display on small-screens

### ISSUE THREAD

**Issue by elisechant** [AusDTO/gov-au-ui-kit#408]
By default breadcrumbs don't display on small screens.

Breadcrumbs should not decide layout. Make the breadcrumbs always visible or provide an optional helper to make then not visible on mobile instead of being default.

<img width="312" alt="screen shot 2016-10-09 at 8 17 34 am" src="https://cloud.githubusercontent.com/assets/2195815/19216000/17e9ed42-8df9-11e6-8501-734e75155741.png">

**Comment by klepas** [comment]
If I recall correctly it was decided to make them hidden by default for the following reasons:

- there wasn’t a satisfactory design for it
- wrapping breadcrumbs tested poorly apparently
- it’s hard to anticipate or prevent wrapping at smaller viewport widths (and thus looked not that great)
- it was deemed that there should and would be other important visual cues on the page to inform the user where they are, as well as nav options to allow for navigating

@elisechant if you re-enabled them in anything you’re working on I’d really like to know how they test with users — happy to revisit this if you have good data. :)
