### ISSUE TITLE
Bug - Unable to install UI kit as a dependency in own npm package

### ISSUE THREAD

**Issue by dlm78** [AusDTO/gov-au-ui-kit#416]
## What I did

I want to pull the UI kit into my own project as part of a build and added it as a dependency in package.json via:

```
"dependencies": {
    "gov-au-ui-kit": "git@github.com:AusDTO/gov-au-ui-kit.git#1.8.0"
  }
```

When running `npm install` I get a permission error for the repo.
### What browser and device I was using

Windows 10 cmd prompt.
## What I expected to see

I expected to see node_modules/gov-au-ui-kit created in my project.
## What I saw

![image](https://cloud.githubusercontent.com/assets/6855995/19423362/55e47a40-946b-11e6-8eb2-dd4d3539446b.png)
[npm-debug.txt](https://github.com/AusDTO/gov-au-ui-kit/files/532340/npm-debug.txt)

**Comment by nathf** [comment]
Try installing via HTTPS not git protocol

```
npm i https://github.com/AusDTO/gov-au-ui-kit.git#1.8.0 -S
```

**Comment by dlm78** [comment]
Installing directly via npm wasn't a problem (presumably because it explicitly used HTTPS). The issue was automated build via package.json.

Replacing

```
dependencies: {
  "gov-au-ui-kit": "git@github.com:AusDTO/gov-au-ui-kit.git#1.8.0",
}
```

with

```
"dependencies": {
    "gov-au-ui-kit": "https://github.com/AusDTO/gov-au-ui-kit.git#1.8.0"
  }
```

worked and the gov-au-ui-kit is successfully pulled in as a dependency. Perhaps the [doco](https://github.com/AusDTO/gov-au-ui-kit/blob/develop/docs/how-dashboards-include-the-uikit.md) can be updated?

Now to integrate into my package via gulp-sass includePaths... :)

Many thanks.

**Comment by klepas** [comment]
@dlm78 Good find. Mhh… shouldn’t cloning via git be available for a public repository, or do we need to change this in our `package.json` over to HTTPS?

**Comment by nathf** [comment]
Cloning via git protocol is tied to your pubkey, essentially only DTO org members can do that. HTTPS should work for everyone as its anonymous.

The two docs in that folder contradict each other slightly, might be worth reviewing them or even combining them.
