### ISSUE TITLE
Refactor and pull over example layouts into the design guide

### ISSUE THREAD

**Issue by klepas** [AusDTO/gov-au-ui-kit#425]
Refactor and pull over any example layouts from the UI-Kit into the `dto-design-guide` repo.

Most of these have a lot of early gov.au beta branding/styling that may need to be reworked.

Check with Donna/the gov.au team on whether these are still current.

**Comment by hannah-ustwo** [comment]
GOV.AU elements removed, by request. Moving to done.
Separated work around example layouts in this ticket: ausdto/dto-design-guide#20
