### ISSUE TITLE
Refactor MVP content for top level pages

### ISSUE THREAD

**Issue by klepas** [AusDTO/gov-au-ui-kit#426]
We need:
- a repo readme (could be the same as homepage, or not)
- a homepage
- getting started
- design principles
- foundations
- components
- patterns
- resources & credits

**Comment by klepas** [comment]
#404 is tracking the design principles page.

**Comment by hannah-ustwo** [comment]
Duplicate/old card - captured in ausdto/dto-design-guide#19
