### ISSUE TITLE
Create a layout that combines collection doc items with the correct SASS comment data

### ISSUE THREAD

**Issue by klepas** [AusDTO/gov-au-ui-kit#427]
The collections are implemented, inc. looping through a collection’s items, but we need a collection.doc layout that allows us to inject the correct corresponding SASS comments into the right ad-hoc `_$collection/$feature.md` file.

I’m thinking of using the name as the primary key to make this link.

**Comment by klepas** [comment]
@petronbot I’m keen to swarm on this ASAP after a release since it’s blocking Jools and I from proceeding on the content refactoring.

**Comment by hannah-ustwo** [comment]
Documented within #18 in ui-kit repo, closing. ausdto/gov-au-ui-kit#18
