### ISSUE TITLE
Refactor SASS comments content into Jekyll collection docs

### ISSUE THREAD

**Issue by klepas** [AusDTO/gov-au-ui-kit#429]
Jools and I need to go through our SASS comments and move all applicable guidance into the `dto-design-guide` repo as collection.doc MD items, and ensure they pull in the correct corresponding SASS comment content that remains as living style guide data within the UI-Kit SASS.

**Comment by hannah-ustwo** [comment]
Covered (partly) by ausdto/dto-design-guide#19
