### ISSUE TITLE
Bug: link styles should have color set using "currentColor"

### ISSUE THREAD

**Issue by elisechant** [AusDTO/gov-au-ui-kit#454]
Link styles should inherit their color from their encapsulated text, set to:

`color: currentColor`

**Comment by dominikwilkowski** [comment]
shouldn't link color always be... link color?

**Comment by elisechant** [comment]
yes, well then define link color. currently body text color, unless i am mistaken

**Comment by DJMyles** [comment]
I'm showing link colours defined as following:

```
header[role='banner'] {
  @include link-colours($non-black, $light-aqua, $non-black);
}

body > main {
  @include link-colours($non-black, $light-aqua, $non-black);
}

footer[role='contentinfo'] {
  @include link-colours($non-black, $light-aqua, $non-black);
}
```

And the mixin syntax:

```
@mixin link-colours($text-colour, $hover-bg-colour, $hover-text-colour: $text-colour) {
   <stuff here...>
}
```

Can you provide an example of where the link colour isn't correct or needs changing?

**Comment by klepas** [comment]
After a chat with @elisechant I’m closing this.

Link styles will be revisited in 2.x.
