### ISSUE TITLE
Skip to main content link

### ISSUE THREAD

**Issue by simonschwartz** [AusDTO/gov-au-ui-kit#67]
For consideration

As a user navigating with keyboard it is helpful to be able to easily skip straight to the main content as it can be bothersome to continuously tab through the same header and navigation components after every page load.

This is usually achieved with a link at the very top of the page that is hidden until focused. The skip links button should link to the id of the main content container on the page

**Comment by maxious** [comment]
webaim.org/techniques/skipnav/ was adapted for https://github.com/AusDTO/gov-au-alpha/blob/93745343c5b39c2fbf652b162d039fa80844ea56/_assets/css/partials/_dto.scss#L2256

Key learning was that you have to add tabindex="-1" to the target https://github.com/AusDTO/gov-au-alpha/blob/93745343c5b39c2fbf652b162d039fa80844ea56/_includes/breadcrumbs.html#L44 if it is not clickable https://stackoverflow.com/questions/3572843/skip-navigation-link-not-working-in-google-chrome

**Comment by TrebBrennan** [comment]
Thanks Simon we've add a backlog `DESIGN-101` item for this :)
Something like this will probably do the trick https://codepen.io/anon/pen/wWgYvK

**Comment by TrebBrennan** [comment]
Fixed in `Bugfix/git issues sprint26` #118
