### ISSUE TITLE
Visual active trail for local navigation

### ISSUE THREAD

**Issue by AlzbetaT** [AusDTO/gov-au-ui-kit#96]
With the local navigation, we would like to bold all the parent/grandparent/etc items, of the current item. 

<img width="370" alt="screen shot 2016-06-30 at 3 09 37 pm" src="https://cloud.githubusercontent.com/assets/19522643/16477410/be8c669e-3ed4-11e6-9f62-a9bcc52bd046.png">

**Comment by klepas** [comment]
@TrebBrennan with the recent localnav changes, I think we’ve provided this now right? (:
