### ISSUE TITLE
[tech support] Two, equal width column

### ISSUE THREAD

**Issue by ltankey** [AusDTO/gov-au-ui-kit#97]
We have an editor page with a preview pane roughly of equal size (image included below). However, we require these two panes be side-by-side with equal widths. Both would presumably be in their own divs.

Questions:
- What is the preferred way of approaching this?
  - Is there a ui-kit pattern for this or will it be bespoke?

![image](https://cloud.githubusercontent.com/assets/5369670/16477810/62bc3700-3ed8-11e6-8453-04b8202c548f.png)

**Comment by TrebBrennan** [comment]
Closing this issue -- I'm working closely with Luke on this one because it's bespoke to their product.
FYI: Having observed user behavior on this feature the recommendation was to test tabs
